config:
  server:
    name: test configuration default update
token:
  #expiration-time: '{cipher}3ccdca853dd3c50d37ffcf18df74f212f19f315c6386cef3f0d8aa5d58475678'
  expiration-time: '{cipher}AQBBaHvYvMKVpwE07a44I8wnOk9KP6Kvsp8gGLsg2SFTNC3fTqtQWTJ0e4wHy5kn+sdBW+LdD3DMjV1V/dXH8UPA4JvDZ7sqvaNKeqnK+og8jDheNqTvupsBt3yp4O2C08zTUBR2iiOkHsGWbvRu33hPPnGmeeNvI0RW4SzpX9YGBke6qUIrTRF9cp6/gB36jaQ5SKUrGbzWgjdDpCenFIQ/RrAyYJRXGIvwskFTYQn4CPPVnpNvEjsmld7yjG47aZ/6+biqf1sxuYvRUgkxZ2wOlBpgDzlu+FyQNs44+JU96EpctVJzqCjPxII8u7ZSTPzRBCh3nxrwSxdfkryzMbeGEY0/PdzCvNVLZrad0LDyuqoRbJlW9NXY5PgJzs8x1PM='
  #secret: '{cipher}6133b1a5492b70c7e419c85ff78636b1397cb5c634fc1f76540a72945b6ca52a4df0460ef8955f63eb1ffd3b49d175812eced861b6900806358afbce685e1add461c6635fcc1184124a7ceaf51b277e2'
  secret: '{cipher}AQAtn5Rq6Url3Vil89eDltAYquSfnX1U34AgAtE6O28mLQCWh+xph0oOYCSh+Pmu/yh619T7YC8o0IfOq7qAeBbZDgQZ4fspYSBkM1pOpugetRHJkixEnPIBO+WVuv1ARFsDBVxUyaNeNAk3ksYpMKbl7rsYTIxqErNsPwW09ZbtxNXghu3FfsRYFrd7ixbdUvYYM6aFokIYZiLQYkMxMOqApfIurNn52v1/faBky8q1viSmKu8g8Bvimo6U6n/LAH814acTBnDnJwu6AErMxmfs+9K5uB9scKxTnQg4TxWwEvlm9I7D/EL26MnCEeTBB5VLtFSY2AERnl8QAssJhiMeIEPX2TXkq/RrCNRCQqHTinH56rjudFnwyPjrwBmN1mKdpAeaeqD6JaoxJ4/kGd8jsMqoDRWIwpzKxzLMlOWg6Dotrk9kgYBOHPZsrp88sYg='
albums:
  url: http://albums-ws//users/%s/albums
  exceptions:
    albums-not-found: User albums not found
custom-eureka:
  password: '{cipher}AQAIhIzCbMWN29sSTeUWkhISu1Wo4UHMwMLGGgF9DPaZ4529FTaqjA7PVjVXaUei8P3t/cQSJXGG2QMyEN5CdW93P08MF7UcKPpniDTAAEoRE+nqm6tUob/yu+pcv+bmyOnCgNcY77DVMzuslqgP3bp8vsJUCPXph+jQKkdUS8VS/kc9miju2Vrc3RwtIw3IX19RV681WU+1lQXTpM0ssSDIjnNkTHpvpR20iiNfI0tkQgYvkRTszw4D+3uGdtg7LxkkdPZg3f0eTBpXRpOscRfPvNuKNUDoJ4H9W/72VMHmMuRNQyhbg1jN/Up3hgnHgKKAUQyPGtOkQVDKunzoC5chW1Ew2ebSlrRfURPDOd2jnzXVHSFQxp6TEqdO01J5myM='
eureka:
  client:
    service-url:
      defaultZone: http://test:${custom-eureka.password}@localhost:8010/eureka
