config:
  server:
    name: test configuration default update
token:
  expiration-time: '{cipher}3ccdca853dd3c50d37ffcf18df74f212f19f315c6386cef3f0d8aa5d58475678'
  #secret: '{cipher}6133b1a5492b70c7e419c85ff78636b1397cb5c634fc1f76540a72945b6ca52a4df0460ef8955f63eb1ffd3b49d175812eced861b6900806358afbce685e1add461c6635fcc1184124a7ceaf51b277e2'
  secret: '{cipher}AQAtn5Rq6Url3Vil89eDltAYquSfnX1U34AgAtE6O28mLQCWh+xph0oOYCSh+Pmu/yh619T7YC8o0IfOq7qAeBbZDgQZ4fspYSBkM1pOpugetRHJkixEnPIBO+WVuv1ARFsDBVxUyaNeNAk3ksYpMKbl7rsYTIxqErNsPwW09ZbtxNXghu3FfsRYFrd7ixbdUvYYM6aFokIYZiLQYkMxMOqApfIurNn52v1/faBky8q1viSmKu8g8Bvimo6U6n/LAH814acTBnDnJwu6AErMxmfs+9K5uB9scKxTnQg4TxWwEvlm9I7D/EL26MnCEeTBB5VLtFSY2AERnl8QAssJhiMeIEPX2TXkq/RrCNRCQqHTinH56rjudFnwyPjrwBmN1mKdpAeaeqD6JaoxJ4/kGd8jsMqoDRWIwpzKxzLMlOWg6Dotrk9kgYBOHPZsrp88sYg='
