spring:
  security:
    user:
      name: test
      password: '{cipher}AQBYqZYVsx10CGreuBba6s85kzXkthODEOIFrOxRF+zgvmnbwIg4gPZDqtr7IqLatOTtlc/wsWIzuBraaQBx3+YtEUMSCxmq966CqYxYwMAGUPJ2A1JL/QHsDJGuJ9HEnsH5VU8+ic4kkCL6R0yHxTIZAPnGHUjbBXc5Izaxll95UBs1+qjqgbOZ2fZNJExR2o/toxrYexvEkzlM9THZHd/URbIz4iChKnXFnaTwjK/jQKTENAo71oIf6uqgiaqu9dsytso9sO0DuJhkHTt78HvVUP0/Eg1qa4d58HgAZVbG8PC7Vf4VzuyyT/ZHvMMJu445cJW99h9EWO5pLKAhlj3TD2uRwIPLaIIWPoDQiu8Hqq9OP3PTuaScQNRdwB7/tfc='
